language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bs' ]; then cd .. && eval "mv $currentfolder generator-bs" && cd generator-bs; fi

